// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDflKYW50ohzBH1NA9iBLlrhUPzgKCDlo',
    appId: '1:129964515872:web:e8526d10c6d5a7d298d245',
    messagingSenderId: '129964515872',
    projectId: 'grounded-cars',
    authDomain: 'grounded-cars.firebaseapp.com',
    storageBucket: 'grounded-cars.firebasestorage.app',
    measurementId: 'G-5KVMY8ZVJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9gIOiwTGBq9dnIRfCOfr644qCrxw2Dys',
    appId: '1:129964515872:android:8248b04822650d7698d245',
    messagingSenderId: '129964515872',
    projectId: 'grounded-cars',
    storageBucket: 'grounded-cars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoZv42ptOpcF4YIXw-KGXxbMMyfvUpYOs',
    appId: '1:129964515872:ios:83fa7548085a4da798d245',
    messagingSenderId: '129964515872',
    projectId: 'grounded-cars',
    storageBucket: 'grounded-cars.firebasestorage.app',
    iosBundleId: 'com.example.groundedCarsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoZv42ptOpcF4YIXw-KGXxbMMyfvUpYOs',
    appId: '1:129964515872:ios:83fa7548085a4da798d245',
    messagingSenderId: '129964515872',
    projectId: 'grounded-cars',
    storageBucket: 'grounded-cars.firebasestorage.app',
    iosBundleId: 'com.example.groundedCarsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDflKYW50ohzBH1NA9iBLlrhUPzgKCDlo',
    appId: '1:129964515872:web:c35333a1bb8b5a7c98d245',
    messagingSenderId: '129964515872',
    projectId: 'grounded-cars',
    authDomain: 'grounded-cars.firebaseapp.com',
    storageBucket: 'grounded-cars.firebasestorage.app',
    measurementId: 'G-3QB28JF096',
  );
}
